config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  resources :users, only: [:show, :new, :create]

  resources :posts, only: [:new, :create, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	has_many :posts

	before_save :email_to_lowercase

	validates :name, presence: true, length: { maximum: 50 }
	  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 8 }

	def email_to_lowercase
		email.downcase!
	end

	def self.generate_token
		SecureRandom.urlsafe_base64
	end

  def self.generate_digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

	def assign_remember_token_and_digest
		self.remember_token = User.generate_token
		update_attribute(:remember_digest, User.generate_digest(remember_token))
	end

	def delete_remember_digest
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	  before_action :check_logged_in, only: [:new, :create]

  def new
  	@post = current_user.posts.new
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		flash[:success] = "Post successful!"
  		redirect_to posts_url
  	else
  		flash.now[:danger] = "Post failed."
  		render 'new'
  	end
  end

  def index
  	@posts = Post.all
  end

	private

  	def check_logged_in
  		if !logged_in?
  			flash[:danger] = "Please log in to create a post."
  			redirect_to login_url
  		end
  	end

  	private

  	def post_params
  		params.require(:post).permit(:content)
  	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		login(user)
  		params[:session][:remember] == '1' ? remember(user) : forget(user)	  		
  		flash[:success] = "Welcome back, #{user.name}!"
  		redirect_to user
  	else
  		flash.now[:danger] = "Incorrect email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	logout if logged_in?
  	redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_logged_in, only: [:show]

	def show
		@user = User.find_by(id: params[:id])
    @posts = @user.posts.all
	end

  def new
  	@user = User.new
  end
  
  def create
  	@user = User.new(user_params)
  	if @user.save
      login(@user)
  		flash[:success] = "Account successfully created."
  		redirect_to @user
  	else
  		flash.now[:danger] = "Account creation failed."
  		render 'new'
  	end
  end

  private

    def check_logged_in
      if !logged_in?
        flash[:danger] = "Please log in to view user feed."
        redirect_to login_url
      end
    end

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.assign_remember_token_and_digest
		cookies.permanent.signed[:user_id] = session[:user_id]
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.delete_remember_digest
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:user_id]
			user = User.find_by(id: cookies.signed[:user_id])
  			if user && user.authenticated?(cookies[:remember_token])
  				login(user)
  				@current_user = user
  			end
		end
	end

	def current_user?(user)
		user == current_user
	end

	def logged_in?
		!current_user.nil?
	end

	def logout
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class='navbar navbar-inverse'>

	<div class='container'>
		<%= link_to "Rails Security Sample", root_path, id: 'logo' %>
		<nav>
			<ul class='nav navbar-nav navbar-right'>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Feed", posts_path %></li>
				<% if !logged_in? %>
					<li><%= link_to "Login", login_path %></li>
				<% else %>
					<li><%= link_to current_user.name, user_path(current_user) %></li>
					<li><%= link_to "Logout", logout_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Security Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  	<div class='container'>
  		<% flash.each do |message_type, message| %>
  			<%= content_tag( :div, message, class: "alert alert-#{message_type}" ) %>
  		<% end %>
    	<%= yield %>
		</div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Post feed</h1>
<br><br>
<% if logged_in? %>
	<%= link_to "Create post", new_post_path %>
<% end %>
<br><br>
<ul class='post-feed'>
	<% @posts.each do |post| %>
		<li>
			<span id='post-name'>
				<% if logged_in? %>
					<%= link_to post.user.name, user_path(post.user) %><br>
				<% else %>
					User's name hidden.<br>
				<% end %>
			</span>
			<span id='post-content'><%= post.content %></span><br>
			<span id='post-ago'>Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
			</li>
	<% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create post</h1>

<div class='container'>
	<div class='row'>
		<div class='col-md-6 col-md-offset-3'>

			<%= form_for @post do |f| %>
				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :content, "New post" %>
				<%= f.text_area :content, class: 'form-control' %>

				<%= f.submit "Create post", class: 'btn btn-primary' %>	

			<% end %>
		</div>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

	<div class='error_messages'>
		<div class='alert alert-danger'>
			<%= pluralize(object.errors.count, "error") %> found.
		</div>
		<ul>
			<% object.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>This Rails app serves one purpose, and one purpose only: to quickly and cleanly illustrate that I understand how to create a secure app that protects users login information and only allows users to view information that they are authorized to see. The app was not intended to be particularly attractive. If you want a better idea of my CSS skills, please see my portfolio at <a href="http://markdking.me">http://markdking.me</a> or some of my other web apps in <a href="https://github.com/gute73">GitHub</a>.</p>

<p>The goal here is to simulate an online environment where users can have free or paid access. Those with free access are not required to log in, but can only view posts and are not allowed to make posts of their own. In addition, the names of the authors of indivdual posts are hidden from users with free access. These features become unlocked for users with paid accounts.  Please note that there is no index page for users, no option to edit or delete accounts, no admin access, no mechanism for paying for the account on the sign up page, etc. The focus here is on the implementation of password security and the management of permissions.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<div class='container'>
		<h1>Rails Security Sample</h1>
		<p><%= link_to "(What is this?)", about_path %></p>
		<% if !logged_in? %>
			<p><%= link_to "Login", login_path, class: 'btn btn-lg btn-primary' %> or <%= link_to "Sign up", signup_path, class: 'btn btn-lg btn-primary' %></p>
		<% else %>
			<p><%= link_to "Create post", new_post_path, class: 'btn btn-lg btn-primary' %> or <%= link_to "View posts", posts_path, class: 'btn btn-lg btn-primary' %></p>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<h1>Create account</h1>

<div class='container'>
	<div class='row'>
		<div class='col-md-6 col-md-offset-3'>

			<%= form_for @user do |f| %>
				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :email %>
				<%= f.email_field :email, class: 'form-control' %>

				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control' %>

				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>

				<%= f.submit "Create account", class: 'btn btn-primary' %>	

			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if current_user?(@user) %>
	<%= link_to "Create post", new_post_path %>
	<br><br>
<% end %>
<ul class='post-feed'>
	<% if @posts.any? %>
		<% @posts.each do |post| %>
			<li>
				<span id='post-content'><%= post.content %></span><br>
				<span id='post-ago'>Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
			</li>
		<% end %>
	<% else %>
		<p>No posts!</p>
	<% end %>
</ul>